name: js_interop_utils
description: A Dart library for seamless interaction with JavaScript using `dart:js_interop`, supporting deep transformations of objects, maps, and arrays.
version: 1.0.8
repository: https://github.com/gmpassos/js_interop_utils

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.2
  dependency_validator: ^4.1.3
